version: 0.2
env:
  variables:
    ECR_REPO: 652023154284.dkr.ecr.us-west-2.amazonaws.com/anycompany/demo
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo "Building a Docker image..."
      - docker build -t python-demo . --file Dockerfile
      - echo "Tagging Docker image for ECR..."
      - docker tag python-demo ${ECR_REPO}:latest
      - echo "Logging into ECR.."
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 652023154284.dkr.ecr.us-west-2.amazonaws.com
      - echo "Pushing Docker image to ECR..."
      - docker push ${ECR_REPO}:latest
      - echo "Done.""